const SUPABASE_URL=(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const SUPABASE_ANON_KEY=process.env.SUPABASE_ANON_KEY||'';
const ALLOWED_ORIGINS=[...(process.env.ACQ_ALLOWED_ORIGINS||'').split(','),process.env.URL||'',process.env.DEPLOY_PRIME_URL||''].map(x=>x.trim()).filter(Boolean);
const AUTH_TIMEOUT_MS=Math.max(500,Number(process.env.ACQ_AUTH_TIMEOUT_MS||2500));
function originFor(event){const origin=event?.headers?.origin||event?.headers?.Origin||'';if(!origin)return null;const ok=ALLOWED_ORIGINS.length?ALLOWED_ORIGINS.includes(origin):/^(https?:\/\/localhost(?::\d+)?|https?:\/\/127\.0\.0\.1(?::\d+)?)$/i.test(origin);return ok?origin:null;}
function cors(event){const origin=originFor(event);return origin?{'access-control-allow-origin':origin,'vary':'Origin','access-control-allow-headers':'Content-Type, Authorization','access-control-allow-methods':'GET,POST,OPTIONS'}:{'access-control-allow-headers':'Content-Type, Authorization','access-control-allow-methods':'GET,POST,OPTIONS'};}
async function fetchWithTimeout(url,options={},timeoutMs=5000){const c=new AbortController();const parent=options?.signal;const onAbort=()=>c.abort();if(parent){if(parent.aborted)c.abort();else parent.addEventListener('abort',onAbort,{once:true});}const t=setTimeout(()=>c.abort(),timeoutMs);try{const requestOptions={...options,signal:c.signal};return await fetch(url,requestOptions);}finally{clearTimeout(t);if(parent)parent.removeEventListener('abort',onAbort);}}
async function requireAuth(event){const h=event.headers||{};const auth=h.authorization||h.Authorization||'';if(!auth.startsWith('Bearer '))return{ok:false,statusCode:401,error:'Authentication required'};if(!SUPABASE_URL||!SUPABASE_ANON_KEY)return{ok:false,statusCode:500,error:'SUPABASE_URL / SUPABASE_ANON_KEY belum dikonfigurasi'};try{const r=await fetchWithTimeout(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:auth}},AUTH_TIMEOUT_MS);if(!r.ok)return{ok:false,statusCode:401,error:'Invalid or expired session'};return{ok:true,user:await r.json()};}catch(e){return{ok:false,statusCode:502,error:e?.name==='AbortError'?'Authentication service timeout':'Authentication service unavailable'};}}
module.exports={cors,requireAuth,fetchWithTimeout};
