import assert from 'node:assert/strict';
import fs from 'node:fs';
import { readReactSource } from './_react_source.mjs';
const intake=fs.readFileSync('src/core/dataIntake.ts','utf8');
const adapter=fs.readFileSync('src/core/fileIntakeAdapters.ts','utf8');
const endpoint=fs.readFileSync('netlify/functions/data-intake-import.js','utf8');
const migration=fs.readFileSync('supabase/migrations/034_data_intake_p0_hardening.sql','utf8');
const main=readReactSource();
assert.match(intake,/periodStart/);
assert.match(intake,/periodEnd/);
assert.match(intake,/periodCount/);
assert.match(intake,/monthlyBreakdown/);
assert.match(adapter,/enrichMonthlyBreakdown/);
assert.match(adapter,/periodCount/);
assert.doesNotMatch(endpoint,/trace_data_intake_imports\?actor_user_id=/);
assert.match(endpoint,/rpc\/trace_transition_data_intake/);
assert.match(endpoint,/p_client_id/);
assert.match(migration,/p_client_id text default null/);
assert.match(migration,/TRACE_IMPORT_CLIENT_REQUIRED/);
assert.match(migration,/trace_is_org_member\(v_client\)/);
assert.match(migration,/drop function if exists public\.trace_transition_data_intake\(text,text,text,text,jsonb,jsonb\)/);
assert.match(main,/const BATCH_SIZE=1000/);
assert.match(main,/i\+=BATCH_SIZE/);
assert.match(main,/result\.periodCount>1/);
console.log('Data Intake P0 hardening static contract: PASS');
