import fs from 'node:fs';
import assert from 'node:assert/strict';
const api=fs.readFileSync('netlify/functions/trace-data.js','utf8');
const main=fs.readFileSync('src/app/main.tsx','utf8');
const sql=fs.readFileSync('supabase/migrations/031_trace_kv_access_boundary_v72.sql','utf8');
assert.match(api,/trace_read_global_kv/);
assert.doesNotMatch(api,/\/rest\/v1\/trace_kv\?key=eq\./);
assert.match(main,/supabase\.rpc\('trace_read_global_kv'/);
assert.match(main,/supabase\.rpc\('trace_upsert_global_kv'/);
assert.match(sql,/create or replace function public\.trace_read_global_kv/);
assert.match(sql,/create or replace function public\.trace_upsert_global_kv/);
assert.match(sql,/revoke all on table public\.trace_kv from anon, authenticated/);
assert.match(sql,/TRACE_GLOBAL_KV_KEY_FORBIDDEN/);
console.log('v72 global KV access boundary: PASS');
