export type ActionStatus='planned'|'in_progress'|'blocked'|'completed'|'cancelled';
export type ActionPriority='P0'|'P1'|'P2'|'P3';
export interface ActionEvidence{source:string;period?:string;value?:string|number;notes?:string}
export interface ActionItem{id:string;title:string;owner:string;priority:ActionPriority;status:ActionStatus;dueDate?:string;measure:string;baseline?:number|null;target?:number|null;evidence:ActionEvidence[];dependencies:string[]}
export interface ActionPlan{clientId:string;objective:string;items:ActionItem[];createdAt:string;version:number}
const validStatuses=new Set<ActionStatus>(['planned','in_progress','blocked','completed','cancelled']);
export function validateActionItem(item:ActionItem){const issues:string[]=[];if(!item.id||!item.title||!item.owner)issues.push('id, title, and owner are required');if(!validStatuses.has(item.status))issues.push('invalid status');if(!item.measure)issues.push('measure is required');if(item.target!=null&&item.baseline!=null&&item.priority==='P0'&&item.target===item.baseline)issues.push('P0 target must differ from baseline');if(item.status==='completed'&&item.evidence.length===0)issues.push('completed action requires evidence');return issues}
export function buildActionPlan(input:{clientId:string;objective:string;items:ActionItem[];now?:string}):ActionPlan{const items=input.items.map(x=>({...x,evidence:[...x.evidence],dependencies:[...x.dependencies]}));const issues=items.flatMap(validateActionItem);if(issues.length)throw new Error(`INVALID_ACTION_PLAN: ${issues.join('; ')}`);return{clientId:input.clientId,objective:input.objective,items,createdAt:input.now??new Date().toISOString(),version:1}}
export function summarizeActionPlan(plan:ActionPlan){const total=plan.items.length;const completed=plan.items.filter(x=>x.status==='completed').length;const blocked=plan.items.filter(x=>x.status==='blocked').length;const weighted=plan.items.reduce((s,x)=>s+(x.status==='completed'?1:x.status==='in_progress'?.5:0),0);return{total,completed,blocked,completionPct:total?Number((completed/total*100).toFixed(1)):0,executionPct:total?Number((weighted/total*100).toFixed(1)):0}}
