export type SecuritySeverity='critical'|'high'|'medium'|'low'|'info';
export type SecurityStatus='confirmed'|'suspected'|'blocked'|'healthy';
export type SecurityCategory='auth'|'rls'|'secrets'|'data_access'|'api'|'dependency'|'anomaly'|'transport';
export interface SecurityEvidence{source:string;detail:string;file?:string;line?:number}
export interface SecurityFinding{id:string;severity:SecuritySeverity;category:SecurityCategory;status:SecurityStatus;title:string;cause:string;impact:string;recommendation:string;evidence:SecurityEvidence[]}
export interface SecurityTelemetryEvent{kind:'auth'|'data_access'|'network'|'runtime'|'supabase'|'job';event:Record<string,unknown>;timestamp?:string}
const rank:Record<SecuritySeverity,number>={critical:5,high:4,medium:3,low:2,info:1};
export function analyzeSecurity(files:Array<{path:string;content:string}>,telemetry:SecurityTelemetryEvent[]=[]):SecurityFinding[]{
 const out:SecurityFinding[]=[]; const add=(x:Omit<SecurityFinding,'id'>,id:string)=>out.push({...x,id});
 for(const file of files){const c=file.content;
  if(/(?:SUPABASE_SERVICE_ROLE_KEY|SERVICE_ROLE|PRIVATE_KEY|SECRET_KEY)\s*=\s*["'`]?\w[\w.\-]{15,}/.test(c)) add({severity:'critical',category:'secrets',status:'confirmed',title:'Potential secret embedded in source',cause:'A privileged/secret key pattern appears in source.',impact:'A leaked repository or bundle could expose privileged credentials.',recommendation:'Remove it from source, rotate it if real, and keep privileged keys server-side only.',evidence:[{source:'static scan',file:file.path,detail:'Secret-like assignment detected.'}]},`secret:${file.path}`);
  if(/createClient\([^\n]*(SERVICE_ROLE|service_role)|Authorization:\s*`Bearer \$\{[^}]*SERVICE_ROLE/i.test(c)) add({severity:'critical',category:'data_access',status:'suspected',title:'Privileged Supabase credential may reach client code',cause:'Client-visible code appears to reference a service-role credential.',impact:'An ordinary user could potentially gain privileged database access.',recommendation:'Use only the publishable/anon key in the browser; keep service-role access inside trusted server functions.',evidence:[{source:'static scan',file:file.path,detail:'Privileged credential reference detected.'}]},`priv-client:${file.path}`);
  if(/localStorage\.(?:setItem|getItem)\([^\n]*(?:token|session|password|secret|apikey)/i.test(c)) add({severity:'high',category:'secrets',status:'suspected',title:'Sensitive authentication material may be stored in localStorage',cause:'Local storage uses a token/session/password/secret-like key.',impact:'XSS or a compromised browser context could expose reusable credentials.',recommendation:'Prefer the auth library session mechanism and secure cookies where applicable; never persist secrets manually.',evidence:[{source:'static scan',file:file.path,detail:'Sensitive localStorage key pattern detected.'}]},`storage-secret:${file.path}`);
  if(/Access-Control-Allow-Origin[^\n]*\*/i.test(c)) add({severity:'medium',category:'transport',status:'confirmed',title:'Wildcard CORS detected',cause:'The response policy allows every origin.',impact:'Cross-origin callers may reach the endpoint if other controls fail.',recommendation:'Use an explicit production origin allowlist.',evidence:[{source:'static scan',file:file.path,detail:'Wildcard CORS policy detected.'}]},`cors:${file.path}`);
 }
 const authFailures=telemetry.filter(x=>x.kind==='auth'&&/fail|denied|invalid|expired|unauthorized|forbidden/i.test(JSON.stringify(x.event))).length;
 if(authFailures>=5) add({severity:'high',category:'anomaly',status:'confirmed',title:'Repeated authentication failures detected',cause:`${authFailures} authentication failure events were recorded.`,impact:'Could indicate credential abuse, session probing, or a misconfigured integration.',recommendation:'Inspect server-side audit evidence, rate-limit the endpoint, revoke suspicious sessions, and review access logs.',evidence:[{source:'runtime telemetry',detail:`${authFailures} matching auth-failure events.`}]},'auth-failure-burst');
 return out.sort((a,b)=>rank[b.severity]-rank[a.severity]||a.id.localeCompare(b.id));
}
export function securityStatus(findings:SecurityFinding[]){if(findings.some(f=>f.status==='confirmed'&&f.severity==='critical'))return 'CRITICAL' as const;if(findings.some(f=>f.status==='confirmed'&&(f.severity==='high'||f.severity==='critical')))return 'HIGH_RISK' as const;if(findings.some(f=>f.status==='suspected'))return 'REVIEW' as const;return 'NO_CONFIRMED_FINDING' as const}
