import type { FinanceComparison } from './finance.js';
import type { DiagnosisReport } from './diagnosis.js';
import type { ActionPlan } from './actionPlan.js';
import type { KPIResult } from './kpi.js';

export interface ReportEvidence { source:string; period?:string; detail:string; }
export interface ConsultingReport { title:string; clientName:string; generatedAt:string; periods:{current:string;previous:string|null}; executiveSummary:string; finance:FinanceComparison; diagnosis:DiagnosisReport; kpis:KPIResult[]; actionPlan?:ActionPlan; evidence:ReportEvidence[]; limitations:string[]; }
export function buildConsultingReport(input:Omit<ConsultingReport,'generatedAt'> & {generatedAt?:string}):ConsultingReport{return{...input,generatedAt:input.generatedAt??new Date().toISOString(),evidence:[...input.evidence],limitations:[...input.limitations]}}
export function reportToPlainText(report:ConsultingReport){const lines=[`# ${report.title}`,`Client: ${report.clientName}`,`Generated: ${report.generatedAt}`,`Period: ${report.periods.current} vs ${report.periods.previous??'tidak tersedia'}`,'',`## Executive Summary`,report.executiveSummary,'',`## Finance`,...report.finance.metrics.map(m=>`${m.metric}: current=${m.current??'N/A'} previous=${m.previous??'N/A'} change=${m.change??'N/A'} changePct=${m.changePct==null?'N/A':m.changePct.toFixed(2)+'%'} formula=${m.formula}`),'',`## Diagnosis`,report.diagnosis.conclusion,...report.diagnosis.findings.map(f=>`- ${f.title}: ${f.problem} Cause: ${f.cause} Recommendation: ${f.recommendation}`),'',`## Evidence`,...report.evidence.map(e=>`- ${e.source}${e.period?` (${e.period})`:''}: ${e.detail}`),'',`## Limitations`,...(report.limitations.length?report.limitations:['Tidak ada limitation yang dicatat.'])];return lines.join('\n')}
export function reportToCSV(report:ConsultingReport){const rows=[['Section','Metric','Current','Previous','Change','Change %','Formula','Status','Source','Period','Detail'],...report.finance.metrics.map(m=>['Finance',m.metric,m.current,m.previous,m.change,m.changePct,m.formula,m.status,'','','']),...report.kpis.map(k=>['KPI',k.name,k.current,k.previous,k.change,k.changePct,k.formula,k.status,k.evidence[0]?.source??'',k.evidence[0]?.period??'',k.conclusion]),...report.evidence.map(e=>['Evidence','', '', '', '', '', '', '',e.source,e.period??'',e.detail]),...report.limitations.map(l=>['Limitation','','','','','','','','','',l])];return rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n')}
