import { useState } from 'react';
import { summarizeFinance, type FinanceRecord, type FinanceStatementSection, type FinanceEvidence } from '../../core/finance';
import { analyzePOSHealth, type POSEvent } from '../../core/posHealth';
import { calculateInventoryVariance, type InventoryMovement, type RecipeComponent } from '../../core/inventoryIntelligence';
import { buildBusinessHealth } from '../../core/businessHealth';
import { buildAlerts } from '../../core/alerts';
import { fmtFieldAmount, getReactSupabase, asArray, useTraceCollections, inputStyle } from './_shared';

export function BusinessHealthView(){
  const [clientId,setClientId]=useState(''); const [saveMessage,setSaveMessage]=useState(''); const [saving,setSaving]=useState(false);
  const clientsLive=useTraceCollections(['trace-clients']);
  const clients=asArray(clientsLive.data['trace-clients']).filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object');
  const live=useTraceCollections([],clientId?['finance','sales','pos_events','inventory_movements','inventory_items','inventory_recipes','alerts','anomalies']:[],clientId);
  const financeRecords:FinanceRecord[]=asArray(live.data.finance).filter((r):r is Record<string,unknown>=>!!r).map(r=>({id:String(r.id),period:String(r.period),amount:Number(r.amount),category:r.category as FinanceRecord['category'],outletId:r.outlet_id?String(r.outlet_id):undefined,evidence:r.evidence_source?{id:String(r.id),source:r.evidence_source as FinanceEvidence['source'],sourceRef:r.evidence_note?String(r.evidence_note):undefined}:undefined,accountLabel:r.account_label?String(r.account_label):undefined,statementSection:r.statement_section as FinanceStatementSection|undefined}));
  const scopedFinance=clientId?asArray(live.data.finance).filter(r=>typeof r==='object'&&r!==null&&String((r as any).client_id)===clientId).map(r=>({id:String((r as any).id),period:String((r as any).period),amount:Number((r as any).amount),category:(r as any).category as FinanceRecord['category'],outletId:(r as any).outlet_id?String((r as any).outlet_id):undefined,evidence:(r as any).evidence_source?{id:String((r as any).id),source:(r as any).evidence_source as FinanceEvidence['source']}:undefined})) : financeRecords;
  const periods=[...new Set(scopedFinance.map(r=>r.period))].sort(); const period=periods.at(-1)??''; const previous=periods.at(-2);
  const summary=summarizeFinance(scopedFinance,period);
  const events:POSEvent[]=asArray(live.data.pos_events).filter((e):e is Record<string,unknown>=>!!e && (!clientId||String((e as any).organization_id)===clientId)).map(e=>({id:String(e.id),organizationId:String(e.organization_id),outletId:e.outlet_id?String(e.outlet_id):undefined,employeeId:e.employee_id?String(e.employee_id):undefined,cashierId:e.cashier_id?String(e.cashier_id):undefined,productId:e.product_id?String(e.product_id):undefined,type:e.event_type as POSEvent['type'],amount:Number(e.amount),occurredAt:String(e.occurred_at),sourceRecordId:e.source_record_id?String(e.source_record_id):undefined}));
  const pos=analyzePOSHealth(events);
  const movements:InventoryMovement[]=asArray(live.data.inventory_movements).filter((e):e is Record<string,unknown>=>!!e && (!clientId||String((e as any).organization_id)===clientId)).map(e=>({id:String(e.id),itemId:String(e.item_id),outletId:e.outlet_id?String(e.outlet_id):undefined,type:e.movement_type as InventoryMovement['type'],qty:Number(e.qty),unitCost:e.unit_cost===null||e.unit_cost===undefined?null:Number(e.unit_cost),occurredAt:String(e.occurred_at)}));
  const recipes:RecipeComponent[]=asArray(live.data.inventory_recipes).map(e=>({productId:String((e as any).product_id),itemId:String((e as any).item_id),qtyPerSale:Number((e as any).qty_per_sale)}));
  const sales=asArray(live.data.sales).filter((e):e is Record<string,unknown>=>!!e && (!clientId||String((e as any).client_id)===clientId)).map(e=>({productId:String(e.product_id??''),qty:Number(e.qty),id:String(e.id)})).filter(e=>e.productId);
  const inventory=calculateInventoryVariance(movements,recipes,sales);
  const evidence=[{id:'finance',metric:'Financial data',status:summary.recordCount?'available':'unavailable',value:summary.operatingProfit,period,source:'Supabase trace_finance_records'} as const,{id:'pos',metric:'POS events',status:events.length?'available':'unavailable',value:events.length,source:'Supabase trace_pos_events'} as const,{id:'inventory',metric:'Inventory movements',status:movements.length?'available':'unavailable',value:movements.length,source:'Supabase trace_inventory_movements'} as const];
  const health=buildBusinessHealth({finance:summary,pos:events.length?pos:null,inventory:inventory.length?inventory:undefined,evidence:[...evidence]});
  const alerts=buildAlerts(pos.anomalies,inventory);
  const persistedAlerts=asArray(live.data.alerts).filter((a):a is Record<string,unknown>=>!!a && (!clientId||String((a as any).organization_id)===clientId));
  const saveSnapshot=async()=>{
    if(!clientId||!period||saving)return; setSaving(true); setSaveMessage('');
    try{
      const supabase=getReactSupabase(); if(!supabase) throw new Error('Supabase belum dikonfigurasi.');
      const year=Number(period.slice(0,4)), month=Number(period.slice(5,7)); const periodEnd=new Date(Date.UTC(year,month,0)).toISOString().slice(0,10); const {data:healthRow,error}=await supabase.rpc('trace_save_business_health_snapshot',{p_organization_id:clientId,p_outlet_id:null,p_period_start:`${period}-01`,p_period_end:periodEnd,p_score:health.score,p_dimensions:health.dimensions,p_evidence:evidence,p_confidence_pct:health.confidencePct,p_methodology:'Business Health v68: weighted available dimensions; missing evidence excluded from score.'});
      if(error) throw error;
      for(const a of pos.anomalies.slice(0,20)){
        const {data:anomaly,error:ae}=await supabase.rpc('trace_record_anomaly',{p_organization_id:clientId,p_outlet_id:null,p_category:a.eventType==='cash_discrepancy'?'cash':a.eventType==='price_override'?'price':a.eventType,p_code:a.code,p_title:a.title,p_severity:a.severity,p_observed:a.observed,p_baseline:a.baseline,p_ratio_pct:a.ratioPct,p_impact_min:a.financialImpact,p_impact_max:a.financialImpact,p_methodology:a.explanation,p_confidence:a.confidence,p_evidence_ids:a.evidenceIds,p_period_start:null,p_period_end:null});
        if(ae) throw ae;
        if(anomaly?.id){ const {error:ale}=await supabase.rpc('trace_create_business_alert',{p_organization_id:clientId,p_anomaly_id:anomaly.id,p_severity:a.severity,p_title:a.title,p_what:a.explanation,p_why:'Pattern dibandingkan dengan evidence yang tersedia.',p_impact:a.financialImpact,p_confidence:a.confidence,p_evidence_ids:a.evidenceIds}); if(ale) throw ale; }
      }
      setSaveMessage(healthRow?'Snapshot health dan findings tersimpan ke Supabase.':'Snapshot tersimpan.');
    }catch(e){setSaveMessage(e instanceof Error?e.message:'Gagal menyimpan health snapshot.');} finally{setSaving(false);}
  };
  const transitionAlert=async(id:string,status:'ACKNOWLEDGED'|'RESOLVED'|'DISMISSED')=>{try{const supabase=getReactSupabase();if(!supabase)throw new Error('Supabase belum dikonfigurasi.');const {error}=await supabase.rpc('trace_transition_business_alert',{p_alert_id:id,p_status:status,p_note:null});if(error)throw error;setSaveMessage(`Alert ${status.toLowerCase()} berhasil.`);}catch(e){setSaveMessage(e instanceof Error?e.message:'Perubahan alert gagal.');}};
  const dimTone=(v:number|null)=>v===null?'neutral':v>=80?'positive':v>=60?'warning':'danger';
  return <div style={{display:'grid',gap:16}}>
    <div className="trace-card" style={{padding:26}}><div className="trace-section-kicker">BUSINESS OPERATING INTELLIGENCE</div><h1 style={{margin:'7px 0 5px',fontSize:30}}>Business Health — apa yang terjadi, kenapa, dan apa yang perlu dilakukan.</h1><div className="trace-muted">Score dihitung hanya dari evidence yang tersedia. Data yang belum ada tidak diperlakukan sebagai nol.</div></div>
    <div className="trace-card"><label>Klien / Scope<select value={clientId} onChange={e=>setClientId(e.target.value)} style={inputStyle}><option value="">Pilih klien — wajib sebelum data dimuat</option>{clients.map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.name??c.business_name??c.id)} · {String(c.id)}</option>)}</select></label>{clientId&&<div className="trace-muted" style={{fontSize:11,marginTop:7}}>Scope terkunci ke klien ini. API juga menerapkan filter server-side.</div>}{!period&&<div className="trace-muted" style={{marginTop:8}}>Belum ada periode finance yang tersedia untuk scope ini.</div>}</div>
    {live.loading?<div className="trace-card">Memuat data evidence…</div>:live.error?<div className="trace-recovery-banner">Data gagal dimuat: {live.error}</div>:<>
      <div className="trace-kpis">
        <div className="trace-card"><div className="trace-muted">Business Health</div><div style={{fontSize:34,fontWeight:850,marginTop:7}}>{health.score===null?'—':`${health.score}/100`}</div><div className="trace-badge" data-tone={dimTone(health.score)}>Evidence {health.confidencePct===null?'—':`${health.confidencePct}%`}</div></div>
        <div className="trace-card"><div className="trace-muted">Revenue · {period||'—'}</div><div style={{fontSize:24,fontWeight:800,marginTop:7}}>{fmtFieldAmount(summary.revenue)}</div><div className="trace-muted" style={{fontSize:11}}>vs {previous||'—'}</div></div>
        <div className="trace-card"><div className="trace-muted">Operating Profit</div><div style={{fontSize:24,fontWeight:800,marginTop:7}}>{fmtFieldAmount(summary.operatingProfit)}</div><div className="trace-muted" style={{fontSize:11}}>{summary.operatingMarginPct===null?'margin belum dapat dihitung':`${summary.operatingMarginPct.toFixed(1)}% margin`}</div></div>
        <div className="trace-card"><div className="trace-muted">POS Health</div><div style={{fontSize:24,fontWeight:800,marginTop:7}}>{pos.score===null?'—':`${pos.score}/100`}</div><div className="trace-muted" style={{fontSize:11}}>{pos.anomalies.length} anomaly terdeteksi</div></div>
      </div>
      <div style={{display:'grid',gridTemplateColumns:'minmax(0,1.2fr) minmax(280px,.8fr)',gap:16}}>
        <div className="trace-card"><strong>Kenapa score seperti ini?</strong><div style={{display:'grid',gap:9,marginTop:12}}>{health.dimensions.map(d=><div key={d.key} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:12,padding:'9px 0',borderTop:'1px solid rgba(23,23,23,.07)'}}><span>{d.label}</span><strong>{d.value===null?'INSUFFICIENT DATA':`${d.value}/100`}</strong></div>)}</div></div>
        <div className="trace-card"><strong>Prioritas tindakan</strong><div style={{display:'grid',gap:10,marginTop:12}}>{alerts.length?alerts.slice(0,5).map(a=><div key={a.id} style={{padding:11,border:'1px solid rgba(23,23,23,.08)',borderRadius:11}}><div className="trace-badge" data-tone={a.severity==='CRITICAL'||a.severity==='HIGH'?'danger':a.severity==='MEDIUM'?'warning':'neutral'}>{a.severity}</div><div style={{fontWeight:750,marginTop:6}}>{a.title}</div><div className="trace-muted" style={{fontSize:11,marginTop:4}}>{a.why}</div></div>):<div className="trace-muted">Tidak ada alert dari evidence yang tersedia.</div>}</div></div>
      </div>
      {persistedAlerts.length>0&&<div className="trace-card"><strong>Alert tersimpan</strong><div style={{display:'grid',gap:8,marginTop:10}}>{persistedAlerts.slice(0,10).map(a=><div key={String(a.id)} style={{padding:11,border:'1px solid rgba(23,23,23,.08)',borderRadius:11}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong>{String(a.title)}</strong><span className="trace-badge" data-tone={String(a.severity)==='HIGH'||String(a.severity)==='CRITICAL'?'danger':'warning'}>{String(a.status)}</span></div><div className="trace-muted" style={{fontSize:11,marginTop:4}}>{String(a.why)}</div>{['OPEN','ACKNOWLEDGED'].includes(String(a.status))&&<div style={{display:'flex',gap:7,marginTop:8}}><button className="trace-icon-btn" onClick={()=>transitionAlert(String(a.id),'ACKNOWLEDGED')}>Acknowledge</button><button className="trace-icon-btn" onClick={()=>transitionAlert(String(a.id),'RESOLVED')}>Resolve</button><button className="trace-icon-btn" onClick={()=>transitionAlert(String(a.id),'DISMISSED')}>Dismiss</button></div>}</div>)}</div></div>}
      <div className="trace-card"><strong>Evidence & limitations</strong><div style={{display:'grid',gap:7,marginTop:10}}>{health.evidence.missing.map(x=><div key={x} className="trace-muted">Belum tersedia: {x}</div>)}{summary.missingMetrics.map(x=><div key={x} className="trace-muted">Finance belum lengkap: {x}</div>)}{inventory.filter(v=>v.status==='INSUFFICIENT_DATA').length>0&&<div className="trace-muted">Inventory: recipe/BOM belum lengkap untuk sebagian item; variance tidak dipaksakan.</div>}<div className="trace-muted">Anomaly bukan bukti fraud. Setiap temuan perlu investigasi dengan evidence asli.</div></div></div>
    </>}
  </div>
}

