import { useEffect, useState } from 'react';
import { Database, Target } from 'lucide-react';
import { calculateFnbTargetPlan, type TargetPlanInput, type TargetPlanResult } from '../../core/fnbTargetPlanning';
import { requireReactSession, loadTraceCollections, asArray, useTraceCollections, money, inputStyle } from './_shared';

export const EMPTY_TARGET:TargetPlanInput={seats:0,tables:0,seatsPerTable:0,turnsPerDay:0,occupancyPct:0,avgTicket:0,operatingDays:30,hoursPerDay:10,peakHoursPerDay:4,peakOccupancyPct:0,parkingSpaces:0,parkingTurnsPerDay:0,parkingConversionPct:0,parkingAvgTicket:0,takeawayOrdersPerDay:0,takeawayConversionPct:100,takeawayAvgTicket:0,staffPerShift:0,shiftsPerDay:1,laborHoursPerStaff:8,wagePerHour:0,rent:0,utilities:0,marketing:0,otherOpex:0,fixedCosts:0,variableCostPct:0,desiredProfit:0,currentRevenue:0};
export function FnbTargetPlanner(){
  const clientsLive=useTraceCollections(['trace-clients']);
  const clients=asArray(clientsLive.data['trace-clients']).filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object');
  const [clientId,setClientId]=useState(''); const [outletId,setOutletId]=useState(''); const [planName,setPlanName]=useState('Target Omset & Kapasitas');
  const [period,setPeriod]=useState(new Date().toISOString().slice(0,7)); const [draft,setDraft]=useState<TargetPlanInput>({...EMPTY_TARGET});
  const [result,setResult]=useState<TargetPlanResult|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [plans,setPlans]=useState<Array<Record<string,unknown>>>([]); const [loading,setLoading]=useState(false);
  const [evidenceLoading,setEvidenceLoading]=useState(false); const [productionEvidence,setProductionEvidence]=useState<{revenue:number|null;transactions:number;avgTicket:number|null;periods:string[]}>({revenue:null,transactions:0,avgTicket:null,periods:[]});
  const set=(k:keyof TargetPlanInput,v:string)=>setDraft(d=>({...d,[k]:Number(v)||0}));
  const calculate=()=>setResult(calculateFnbTargetPlan(draft));
  const loadPlans=async()=>{if(!clientId)return;setLoading(true);try{const supabase=await requireReactSession();const {data,error}=await supabase.from('trace_fnb_target_plans').select('*').eq('client_id',clientId).order('period',{ascending:false}).limit(30);if(error)throw error;setPlans(asArray(data).filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object'));}catch(e){setMessage(e instanceof Error?e.message:'Gagal memuat target.')}finally{setLoading(false)}};
  const loadProductionEvidence=async()=>{if(!clientId)return;setEvidenceLoading(true);try{const {data}=await loadTraceCollections([],['finance','sales'],clientId);const finance=asArray(data.finance).filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object');const sales=asArray(data.sales).filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object');const month=period;const financeMonth=finance.filter(x=>String(x.period??'').slice(0,7)===month);const revenue=financeMonth.filter(x=>String(x.category??'')==='revenue').reduce((n,x)=>n+Number(x.amount)||0,0);const salesMonth=sales.filter(x=>String(x.sold_at??'').slice(0,7)===month);const tx=salesMonth.reduce((n,x)=>n+Number(x.qty)||0,0);const salesRevenue=salesMonth.reduce((n,x)=>n+Number(x.qty||0)*Number(x.unit_price||0),0);const actualRevenue=revenue>0?revenue:(salesRevenue>0?salesRevenue:null);setProductionEvidence({revenue:actualRevenue,transactions:tx,avgTicket:tx>0&&salesRevenue>0?salesRevenue/tx:null,periods:[month]});}catch(e){setMessage(e instanceof Error?e.message:'Evidence production belum dapat dibaca.');}finally{setEvidenceLoading(false)}};
  useEffect(()=>{void loadPlans();void loadProductionEvidence()},[clientId,period]);
  const useProductionEvidence=()=>setDraft(d=>({...d,currentRevenue:productionEvidence.revenue??d.currentRevenue,avgTicket:productionEvidence.avgTicket??d.avgTicket}));
  const save=async()=>{if(!clientId||!result)return;setSaving(true);setMessage('');try{const supabase=await requireReactSession();const {data,error}=await supabase.rpc('trace_upsert_fnb_target_plan',{p_id:null,p_client_id:clientId,p_outlet_id:outletId||null,p_plan_name:planName.trim()||'Target Omset & Kapasitas',p_period:`${period}-01`,p_assumptions:draft,p_result:result,p_evidence_source:'manual',p_evidence_note:'Asumsi kapasitas, biaya, channel, dan target diinput manual oleh konsultan.'});if(error)throw error;setMessage(`Plan tersimpan. ID ${String(data)}`);await loadPlans();}catch(e){setMessage(e instanceof Error?e.message:'Gagal menyimpan target.')}finally{setSaving(false)}};
  const Field=({label,k,step='any'}:{label:string,k:keyof TargetPlanInput,step?:string})=><label style={{display:'grid',gap:5,fontSize:12}}>{label}<input type="number" min="0" step={step} value={String(draft[k]??0)} onChange={e=>set(k,e.target.value)} style={inputStyle}/></label>;
  return <div style={{display:'grid',gap:16}}>
    <div className="trace-card" style={{padding:26}}><div className="trace-muted" style={{fontSize:12}}>F&B CONSULTING · TARGET & CAPACITY ENGINE</div><h1 style={{margin:'7px 0 5px',fontSize:30}}>Dari diagnosis → target → kapasitas → action.</h1><div className="trace-muted">TRACE menghitung target omset dari kebutuhan profit dan menguji apakah outlet sanggup mencapainya lewat kursi, meja, turn, okupansi, jam peak, parkir, takeaway, labor, dan struktur biaya.</div></div>
    <div className="trace-card" style={{display:'grid',gap:12}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label>Klien<select value={clientId} onChange={e=>setClientId(e.target.value)} style={inputStyle}><option value="">Pilih klien</option>{clients.map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.name??c.business_name??c.id)}</option>)}</select></label><label>Periode<input type="month" value={period} onChange={e=>setPeriod(e.target.value)} style={inputStyle}/></label></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label>Nama Plan<input value={planName} onChange={e=>setPlanName(e.target.value)} style={inputStyle}/></label><label>Outlet ID (opsional)<input value={outletId} onChange={e=>setOutletId(e.target.value)} placeholder="UUID outlet bila diperlukan" style={inputStyle}/></label></div></div>
    {clientId&&<>
      <div className="trace-card"><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><strong>Evidence production · {period}</strong><div className="trace-muted" style={{fontSize:12,marginTop:4}}>Target boleh dimodelkan manual, tetapi omset dan average ticket dapat ditarik dari Finance/Sales production sebagai baseline.</div></div><button onClick={useProductionEvidence} disabled={evidenceLoading||productionEvidence.revenue===null} style={{border:0,borderRadius:9,padding:'8px 11px',background:productionEvidence.revenue===null?'#eee':'#171717',color:productionEvidence.revenue===null?'#999':'#fff',fontWeight:700}}>{evidenceLoading?'Membaca…':'Gunakan evidence production'}</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:9,marginTop:12}}><div><div className="trace-muted" style={{fontSize:10}}>Revenue evidence</div><b>{productionEvidence.revenue===null?'—':money(productionEvidence.revenue)}</b></div><div><div className="trace-muted" style={{fontSize:10}}>Transactions</div><b>{productionEvidence.transactions.toLocaleString('id-ID')}</b></div><div><div className="trace-muted" style={{fontSize:10}}>Avg ticket</div><b>{productionEvidence.avgTicket===null?'—':money(productionEvidence.avgTicket)}</b></div></div></div>
      <div className="trace-card"><strong>1 · Kapasitas Dine-In</strong><div className="trace-muted" style={{fontSize:12,margin:'5px 0 12px'}}>Basis: kapasitas fisik × utilisasi. Isi angka aktual, bukan angka ideal.</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10}}><Field label="Jumlah kursi" k="seats"/><Field label="Jumlah meja" k="tables"/><Field label="Kursi / meja" k="seatsPerTable"/><Field label="Turn / hari" k="turnsPerDay" step="0.1"/><Field label="Okupansi %" k="occupancyPct" step="0.1"/><Field label="Avg ticket" k="avgTicket"/><Field label="Hari operasional" k="operatingDays"/><Field label="Jam buka / hari" k="hoursPerDay"/><Field label="Jam peak / hari" k="peakHoursPerDay" step="0.1"/><Field label="Okupansi peak %" k="peakOccupancyPct" step="0.1"/></div></div>
      <div className="trace-card"><strong>2 · Parkir & Channel Non-Dine-In</strong><div className="trace-muted" style={{fontSize:12,margin:'5px 0 12px'}}>Parkir dipakai sebagai proxy demand hanya jika conversion aktual diketahui. Jangan menganggap semua kendaraan = customer.</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10}}><Field label="Slot parkir" k="parkingSpaces"/><Field label="Turn parkir / hari" k="parkingTurnsPerDay" step="0.1"/><Field label="Conversion parkir %" k="parkingConversionPct" step="0.1"/><Field label="Avg ticket parkir" k="parkingAvgTicket"/><Field label="Order takeaway / hari" k="takeawayOrdersPerDay"/><Field label="Conversion takeaway %" k="takeawayConversionPct" step="0.1"/><Field label="Avg ticket takeaway" k="takeawayAvgTicket"/></div></div>
      <div className="trace-card"><strong>3 · Labor Capacity</strong><div className="trace-muted" style={{fontSize:12,margin:'5px 0 12px'}}>Bukan hanya biaya labor: TRACE menghitung kapasitas orang yang dibutuhkan untuk menjalankan outlet.</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10}}><Field label="Staff / shift" k="staffPerShift"/><Field label="Shift / hari" k="shiftsPerDay"/><Field label="Jam kerja / staff" k="laborHoursPerStaff"/><Field label="Upah / jam" k="wagePerHour"/></div></div>
      <div className="trace-card"><strong>4 · Struktur Biaya & Target Profit</strong><div className="trace-muted" style={{fontSize:12,margin:'5px 0 12px'}}>Fixed cost total boleh diisi langsung. Jika detail diisi, TRACE menghitung detailnya dan menjadikannya bagian dari model.</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10}}><Field label="Fixed cost lain / bulan" k="fixedCosts"/><Field label="Variable cost %" k="variableCostPct" step="0.1"/><Field label="Target profit / bulan" k="desiredProfit"/><Field label="Omset aktual / bulan" k="currentRevenue"/><Field label="Rent" k="rent"/><Field label="Utilities" k="utilities"/><Field label="Marketing" k="marketing"/><Field label="OPEX lain" k="otherOpex"/></div><button onClick={calculate} style={{marginTop:14,border:0,borderRadius:9,padding:'10px 15px',background:'#171717',color:'#fff',fontWeight:800,cursor:'pointer'}}>Hitung & Analisis</button></div>
      {result&&<div className="trace-card" style={{display:'grid',gap:14}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><strong style={{fontSize:19}}>Consultant Target Board</strong><div className="trace-muted" style={{fontSize:12,marginTop:4}}>Semua angka berasal dari input + formula engine. Tidak ada angka dummy.</div></div><span className="trace-badge">{result.achievableBySeatCapacity?'TARGET MASUK KAPASITAS':'TARGET MELEBIHI KAPASITAS'}</span></div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(5,minmax(0,1fr))',gap:9}}>{[['Break-even',result.breakEvenRevenue],['Target profit',result.profitTargetRevenue],['Target omset',result.targetRevenue],['Kapasitas omset',result.capacityRevenueMonthly],['Utilisasi target',result.capacityUtilizationPct]].map(([k,v])=><div key={String(k)} style={{padding:12,border:'1px solid rgba(23,23,23,.08)',borderRadius:10}}><div className="trace-muted" style={{fontSize:10}}>{k}</div><strong style={{display:'block',marginTop:5}}>{String(k)==='Utilisasi target'?`${Number(v).toFixed(1)}%`:money(Number(v))}</strong></div>)}</div>
        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:10}}><div style={{padding:13,border:'1px solid rgba(23,23,23,.08)',borderRadius:10}}><strong>Target harian</strong><div style={{fontSize:22,fontWeight:800,marginTop:5}}>{money(result.targetDailyRevenue)}</div><div className="trace-muted" style={{fontSize:12,marginTop:4}}>≈ {result.targetTicketCountDaily.toFixed(1)} transaksi/hari</div></div><div style={{padding:13,border:'1px solid rgba(23,23,23,.08)',borderRadius:10}}><strong>Target operasi</strong><div style={{fontSize:18,fontWeight:800,marginTop:5}}>{result.targetSeatTurnsDaily.toFixed(2)} turn efektif/hari</div><div className="trace-muted" style={{fontSize:12}}>Required occupancy ≈ {result.requiredOccupancyPct.toFixed(1)}%</div></div><div style={{padding:13,border:'1px solid rgba(23,23,23,.08)',borderRadius:10}}><strong>Bottleneck</strong><div style={{fontSize:18,fontWeight:800,marginTop:5}}>{result.bottleneck==='none'?'Tidak terdeteksi':result.bottleneck}</div><div className="trace-muted" style={{fontSize:12}}>BE ≈ {result.breakEvenTransactionsDaily.toFixed(1)} transaksi/hari</div></div></div>
        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div className="trace-card"><strong>Labor & OPEX</strong><div style={{fontSize:12,marginTop:7}}>Labor model: {money(result.laborCostMonthly)}/bulan ({result.laborPctOfTarget.toFixed(1)}% dari target).</div><div style={{fontSize:12,marginTop:5}}>Rent {money(result.fixedCostBreakdown.rent)} · Utilities {money(result.fixedCostBreakdown.utilities)} · Marketing {money(result.fixedCostBreakdown.marketing)} · OPEX lain {money(result.fixedCostBreakdown.otherOpex)}</div></div><div className="trace-card"><strong>Scenario</strong>{result.scenarios.map(s=><div key={s.name} style={{display:'grid',gridTemplateColumns:'100px 1fr 1fr',gap:8,fontSize:12,padding:'5px 0',borderTop:'1px solid rgba(23,23,23,.06)'}}><b>{s.name}</b><span>{money(s.revenue)}</span><span>Profit {money(s.profit)}</span></div>)}</div></div>
        <div style={{fontSize:12}}><strong>Basis perhitungan:</strong> {result.assumptions.join(' · ')}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={save} disabled={saving} style={{border:0,borderRadius:9,padding:'10px 15px',background:saving?'#ddd':'#171717',color:saving?'#777':'#fff',fontWeight:800}}>{saving?'Menyimpan…':'Simpan Plan ke Database'}</button>{message&&<span className="trace-muted" style={{alignSelf:'center'}}>{message}</span>}</div>
      </div>}
      <div className="trace-card"><div style={{display:'flex',justifyContent:'space-between'}}><strong>Saved Plans</strong><span className="trace-muted">{loading?'Memuat…':`${plans.length} plan`}</span></div>{plans.slice(0,10).map(p=><div key={String(p.id)} style={{display:'flex',justifyContent:'space-between',gap:10,padding:'9px 0',borderTop:'1px solid rgba(23,23,23,.07)',fontSize:12}}><span><b>{String(p.plan_name)}</b> · {String(p.period)}</span><span>{money(Number((p.result as Record<string,unknown>)?.targetRevenue))}</span></div>)}{!loading&&plans.length===0&&<div className="trace-muted" style={{marginTop:8}}>Belum ada plan tersimpan.</div>}</div>
    </>}
  </div>;
}

