import { useState } from 'react';
import { asArray, useTraceCollections, inputStyle } from './_shared';

export function TeamView(){
  const [clientId,setClientId]=useState('');
  const clientsLive=useTraceCollections(['trace-clients']);
  const clients=asArray(clientsLive.data['trace-clients']).filter((x):x is Record<string,unknown>=>!!x&&typeof x==='object');
  const live=useTraceCollections(['trace-team'],clientId?['tasks']:[],clientId);
  const members=asArray(live.data['trace-team']);
  const tasks=asArray(live.data['tasks']);
  const taskObjects=tasks.filter((x):x is Record<string,unknown>=>typeof x==='object'&&x!==null);
  const open=taskObjects.filter(t=>['open','in_progress','blocked'].includes(String(t.status))).length;
  const done=taskObjects.filter(t=>String(t.status)==='done').length;
  return <div style={{display:'grid',gap:16}}><div className="trace-card" style={{padding:26}}><div className="trace-muted" style={{fontSize:12}}>TEAM · COLLABORATION OS</div><h1 style={{margin:'7px 0 5px',fontSize:30}}>Ownership jelas, perubahan dapat ditelusuri.</h1><div className="trace-muted">Anggota TRACE bersifat global; task selalu ditampilkan dalam scope satu klien agar pekerjaan tidak tertukar.</div></div><div className="trace-card"><label>Klien / Scope<select value={clientId} onChange={e=>setClientId(e.target.value)} style={inputStyle}><option value="">Pilih klien untuk melihat task</option>{clients.map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.name??c.business_name??c.id)}</option>)}</select></label></div><div className="trace-kpis"><div className="trace-card"><div className="trace-muted">Anggota</div><b style={{fontSize:28}}>{clientsLive.loading?'…':clientsLive.error?'—':members.length}</b></div><div className="trace-card"><div className="trace-muted">Task aktif</div><b style={{fontSize:28}}>{clientId?(live.loading?'…':live.error?'—':open):'—'}</b></div><div className="trace-card"><div className="trace-muted">Task selesai</div><b style={{fontSize:28}}>{clientId?(live.loading?'…':live.error?'—':done):'—'}</b></div></div><div className="trace-card"><strong>Production collaboration</strong><div className="trace-muted" style={{marginTop:7}}>{!clientId?'Pilih klien. TRACE tidak memuat task lintas-klien ke layar ini.':live.error||(!live.loading&&live.unavailable.length?`Sumber tidak tersedia: ${live.unavailable.join(', ')}.`:'Task relational tersedia untuk scope klien terpilih.')}</div>{clientId&&!live.loading&&!live.error&&taskObjects.slice(0,20).map((task,index)=><div key={String(task.id??index)} style={{padding:'11px 0',borderTop:'1px solid rgba(23,23,23,.08)',fontSize:13}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>{String(task.title??'Untitled task')}</strong><span className="trace-muted">{String(task.status??'unknown')} · {String(task.priority??'')}</span></div><div className="trace-muted" style={{fontSize:11,marginTop:4}}>Client: {String(task.client_id??clientId)} · Due: {String(task.due_date??'—')}</div></div>)}</div></div>
}
