-- Additive governance/security layer. No existing tables are dropped.
create table if not exists public.trace_ai_approvals(id uuid primary key default gen_random_uuid(),actor_user_id uuid not null references auth.users(id) on delete restrict,action text not null check(action in('apply_patch','commit','push','merge','migrate','deploy')),environment text not null check(environment in('workspace','staging','production')),scope_hash text not null,approved_at timestamptz not null default now(),expires_at timestamptz,revoked_at timestamptz,metadata jsonb not null default '{}'::jsonb);
create table if not exists public.trace_security_events(id uuid primary key default gen_random_uuid(),actor_user_id uuid references auth.users(id) on delete set null,kind text not null check(kind in('auth','data_access','network','runtime','supabase','job')),severity text not null default 'info' check(severity in('critical','high','medium','low','info')),payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.trace_ai_approvals enable row level security; alter table public.trace_security_events enable row level security;
drop policy if exists trace_ai_approvals_team_read on public.trace_ai_approvals; create policy trace_ai_approvals_team_read on public.trace_ai_approvals for select to authenticated using(public.trace_is_team_member());
drop policy if exists trace_ai_approvals_leader_insert on public.trace_ai_approvals; create policy trace_ai_approvals_leader_insert on public.trace_ai_approvals for insert to authenticated with check(public.trace_is_leader() and actor_user_id=auth.uid());
drop policy if exists trace_security_events_team_read on public.trace_security_events; create policy trace_security_events_team_read on public.trace_security_events for select to authenticated using(public.trace_is_team_member());
drop policy if exists trace_security_events_own_insert on public.trace_security_events; create policy trace_security_events_own_insert on public.trace_security_events for insert to authenticated with check(actor_user_id=auth.uid());
revoke all on public.trace_ai_approvals from anon; revoke all on public.trace_security_events from anon; grant select,insert on public.trace_ai_approvals to authenticated; grant select,insert on public.trace_security_events to authenticated;
-- No UPDATE/DELETE policies: security evidence is append-only.
